<?php

/**
 * Implements hook_wysiwyg_editor_js_settings_alter().
 *
 * Ensure the plugin js is loaded if buttons are added to ckeditor config.
 */
function folwell_wysiwyg_editor_js_settings_alter(array &$settings) {
  foreach (array_keys($settings['editor']['formats']) as $text_format_id) {
    if ($settings['editor']['formats'][$text_format_id]['editor'] === 'ckeditor') {
      if (strpos($settings['editor']['formats'][$text_format_id]['editorSettings']['extraPlugins'], 'fwcallout') !== FALSE) {
        $settings['editor']['formats'][$text_format_id]['editorSettings']['extraPlugins'] .= ',fwcallout';
      }
      if (strpos($settings['editor']['formats'][$text_format_id]['editorSettings']['extraPlugins'], 'fwpullquote') !== FALSE) {
        $settings['editor']['formats'][$text_format_id]['editorSettings']['extraPlugins'] .= ',fwpullquote';
      }
      $settings['editor']['formats'][$text_format_id]['editorSettings']['customConfig'] =
        base_path() . drupal_get_path('module', 'folwell_wysiwyg') . '/js/editorConfig.js';
    }
  }
}
