<?php
/**
 * @file
 * Folwell Paragraphs hook implementations
 */

/**
 * Implements hook_theme()
 */
function folwell_paragraphs_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__folwell_accordion' => [
      'base hook' => 'paragraph'
    ],
    'paragraph__fa_accordion_item' => [
      'base hook' => 'paragraph'
    ],
    'paragraph__fa_table' => [
      'base hook' => 'paragraph'
    ],
    'paragraph__fa_text_with_optional_header' => [
      'base hook' => 'paragraph'
    ],
    'paragraph__folwell_callout' => [
      'base hook' => 'paragraph'
    ],
    'paragraph__folwell_overlay' => [
      'base hook' => 'paragraph'
    ]
  ];
}

function folwell_paragraphs_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $type = $paragraph->getType();
  if ($type == 'folwell_accordion') {
    $variables['#attached']['library'][] = 'folwell_components/folwell_accordion';
  }
  if ($type == 'folwell_callout' || $type == 'folwell_overlay') {
    $variables['#attached']['library'][] = 'folwell_components/fwcallout';
    if ($type == 'folwell_callout') {
      $style_field = $variables['content']['field_fw_callout_style']['#items'];
      $variables['style_class'] = $style_field->get(0)->getString();
    }
  }
}